### PR TITLE
Fix memory leaks

### LINKED ISSUE #3: strings inside fixed structure array leaked
Code to reproduce:
```c
struct Test tests[] = {{"first", 1}, {"second", 2},{"third", 3}};
tpl_node *tn;
tn = tpl_map("S(si)#", &tests, 3);
tpl_pack(tn, 0);
tpl_dump(tn, TPL_MEM|TPL_PREALLOCD, buffer, 5000);
tpl_free(tn);
```
This will leak 2 strings: `second` and `third`. Basically for cases like this, only the string from the first array is released.

The problem is that in tpl_free, for case TPL_TYPE_POUND, data is just removed, and number of structures in array is lost.

### PR DESCRIPTION
**Pull request by tbeu**
Fix memory leaks for the case of strings in array of structures.

This is a resubmission of #4 from @andrei-diaconu to fix #3.

### CODE REVIEW

File: src/tpl.c [hunk 1]
```diff
@@ -707,12 +707,20 @@ TPL_API void tpl_free(tpl_node *r) {
...
-                      char *str = ((char**)c->data)[i];
-                      if (str) {
-                        tpl_hook.free(str);
-                        ((char**)c->data)[i] = NULL;
-                      }
+                    num = 1;
+                    nxtc = c->next;
+                    while (nxtc) {
+                        if (nxtc->type == TPL_TYPE_POUND) {
+                            num = nxtc->num;
```
Comment (troydhanson) [inline src/tpl.c]: should this be multiplicative? num *= nxtc->num

**Comment by troydhanson** [comment]
Well, first an apology. This has been sitting open for almost four years. As I've said elsewhere, I have zero time for tpl and I've resisted merging the change because I wasn't sure about it. For sure, it makes valgrind happy that the leak is fixed. But it also satisfies valgrind if I use the change shown in my comment. I worry that if we merge it, the fix may be imperfect. Do you both have an opinion- is it better to merge a possible fix or to leave an obvious bug?

**Comment by andrei-diaconu** [comment]
I have been using my fork that contains this fix and it worked well. For me, this fix is a must. Without it, I cannot use the library. At the moment I don't have the time understand again the code. But if you are not in a hurry to close the ticket now, I could try to understand, and check which is the correct solution.

**Comment by tbeu** [comment]
Thanks @andrei-diaconu for your offer to get it sorted out again. Your input is appreciated. I'd also prefer to see this issue fixed.

**Comment by troydhanson** [comment]
I convinced myself that @andrei-diaconu has the right solution here. I also ran a bunch of tests under valgrind showing my edit is not needed. I also tested with a number of similar format strings like S(s#)# and S(s)##. It worked in all these cases. I approve merging. @tbeu if you agree please go ahead. Thank you for waiting an exceptionally long time and for bringing it back to my attention.
